# MegaLinter configuration for claude-flake project

# Enable common languages with sensible defaults
ENABLE:
  - GO
  - PYTHON
  - JAVASCRIPT
  - RUST
  - BASH
  - MARKDOWN
  - YAML
  - JSON

# Apply fixes automatically (matches smart-lint.sh behavior)
APPLY_FIXES: all

# Output configuration for script parsing - disable file reports to avoid caching issues
REPORT_OUTPUT_FOLDER: megalinter-reports
SHOW_ELAPSED_TIME: true

# File filtering - exclude common build/cache directories
FILTER_REGEX_EXCLUDE: |
  (result/|/nix/store/|\.git/|node_modules/|\.venv/|target/|\.mypy_cache/|\.pytest_cache/|__pycache__/)

# Disable noisy linters for automated use
DISABLE_LINTERS:
  - SPELL_CSPELL
  - COPYPASTE_JSCPD
  - REPOSITORY_SECRETLINT

# Shellcheck configuration - disable SC1091 for missing external files
BASH_SHELLCHECK_ARGUMENTS: "--exclude=SC1091"

# Performance settings
PARALLEL: true
SHOW_SKIPPED_LINTERS: false
CLEAR_REPORT_FOLDER: true
LOG_LEVEL: "INFO"

# Force clear cache
MEGALINTER_PRECOMMANDS:
  - command: rm -rf /tmp/lint/megalinter-reports || true
    description: "Clear previous reports"
EOF < /dev/null