# lib/envrc-templates.nix - .envrc template generation for project types
{ lib, ... }:

{
  # Generate .envrc content for a specific project type
  generateEnvrc =
    projectType: flakeUrl:
    let
      templates = {
        rust = ''
          # Generated by claude-flake init-project
          # Rust development environment with enhanced tooling

          use flake ${flakeUrl}#rust-dev

          # Rust-specific environment variables
          export RUST_BACKTRACE=1
          export CARGO_HOME="$PWD/.cargo"

          # Load additional tools if available
          if command -v rust-analyzer >/dev/null 2>&1; then
            export PATH="$PATH:$(dirname $(which rust-analyzer))"
          fi
        '';

        python = ''
          # Generated by claude-flake init-project
          # Python development environment with enhanced tooling

          use flake ${flakeUrl}#python-dev

          # Python-specific environment variables
          export PYTHONPATH="$PWD:$PYTHONPATH"
          export PIP_REQUIRE_VIRTUALENV=true

          # Poetry configuration
          if [ -f pyproject.toml ]; then
            export POETRY_VENV_IN_PROJECT=true
          fi
        '';

        nodejs = ''
          # Generated by claude-flake init-project
          # Node.js development environment with enhanced tooling

          use flake ${flakeUrl}#nodejs-dev

          # Node.js-specific environment variables
          export NODE_ENV=development
          export NPM_CONFIG_PREFIX="$PWD/.npm-global"
          export PATH="$PWD/node_modules/.bin:$PATH"

          # Detect package manager
          if [ -f yarn.lock ]; then
            echo "Using Yarn package manager"
          elif [ -f pnpm-lock.yaml ]; then
            echo "Using pnpm package manager"
          fi
        '';

        go = ''
          # Generated by claude-flake init-project
          # Go development environment with enhanced tooling

          use flake ${flakeUrl}#go-dev

          # Go-specific environment variables
          export GOPATH="$PWD/.go"
          export GOPROXY=https://proxy.golang.org,direct
          export GOSUMDB=sum.golang.org
          export CGO_ENABLED=1

          # Create GOPATH if it doesn't exist
          mkdir -p "$GOPATH"
        '';

        nix = ''
          # Generated by claude-flake init-project
          # Nix development environment with enhanced tooling

          use flake ${flakeUrl}#nix-dev

          # Nix-specific environment variables
          export NIX_PATH="nixpkgs=channel:nixos-unstable"

          # Enable experimental features for development
          export NIX_CONFIG="experimental-features = nix-command flakes"

          # Detect project type
          if [ -f flake.nix ]; then
            echo "Nix flake project detected"
            use flake .
          fi
        '';

        universal = ''
          # Generated by claude-flake init-project
          # Universal development environment

          use flake ${flakeUrl}#universal-dev

          # Universal environment variables
          export EDITOR=''${EDITOR:-nvim}
          export PAGER=''${PAGER:-bat}

          # Load project-specific configuration if available
          if [ -f .claude-env ]; then
            source .claude-env
          fi
        '';
      };
    in
    templates.${projectType} or templates.universal;

  # Generate devShell configuration for flake.nix integration
  generateDevShell =
    projectType: pkgs:
    let
      languagePackages = import ./language-packages.nix { inherit pkgs; };
      packages = languagePackages.getPackagesForType projectType;
      shellHook = languagePackages.getShellHook projectType;
    in
    ''
      ${projectType}-dev = pkgs.mkShell {
        buildInputs = with pkgs; ${
          lib.concatStringsSep " " (map (pkg: pkg.pname or (toString pkg)) packages)
        };

        shellHook = '''
          ${shellHook}

          # Project-specific setup
          if [ -f .claude-env ]; then
            echo "Loading project overrides from .claude-env"
            source .claude-env
          fi
        ''';
      };
    '';

  # Generate complete .envrc with error handling
  generateCompleteEnvrc =
    projectType: flakeUrl:
    let
      baseEnvrc = generateEnvrc projectType flakeUrl;
    in
    ''
      #!/usr/bin/env bash
      # Claude-Flake Enhanced Project Environment
      # Generated for: ${projectType} project
      # Flake source: ${flakeUrl}

      ${baseEnvrc}

      # Error handling and fallback
      if ! command -v direnv >/dev/null 2>&1; then
        echo "⚠️  direnv not found. Install with: nix profile install nixpkgs#direnv"
        exit 1
      fi

      # Success message
      echo "✅ Enhanced ${projectType} environment loaded via claude-flake"

      # Show available commands based on project type
      case "${projectType}" in
        rust)
          echo "💡 Try: cargo build, cargo test, cargo clippy"
          ;;
        python)
          echo "💡 Try: poetry install, poetry run, pytest"
          ;;
        nodejs)
          echo "💡 Try: npm install, yarn install, npm test"
          ;;
        go)
          echo "💡 Try: go build, go test, go mod tidy"
          ;;
        nix)
          echo "💡 Try: nix build, nix develop, nixfmt ."
          ;;
      esac
    '';

  # Validate project directory before generating .envrc
  validateProjectDirectory =
    projectPath:
    let
      isWritable = builtins.pathExists projectPath;
      hasGit = builtins.pathExists "${projectPath}/.git";
      hasEnvrc = builtins.pathExists "${projectPath}/.envrc";
    in
    {
      valid = isWritable;
      warnings =
        lib.optionals hasEnvrc [ "Existing .envrc will be overwritten" ]
        ++ lib.optionals (!hasGit) [ "Not a git repository - consider running 'git init'" ];
      errors = lib.optionals (!isWritable) [ "Directory not writable" ];
    };
}
