name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: genai-nix-flake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      
      - name: Check all flakes
        run: |
          set -euo pipefail
          echo "Checking dev-shells flake..."
          nix flake check ./dev-shells
          
          echo "Checking home-manager flake..."
          nix flake check ./home-manager
          
          echo "Checking main flake (with impure flag for local paths)..."
          nix flake check --impure
      
      - name: Format check
        run: |
          set -euo pipefail
          nix develop --command bash -c "
            find . -name '*.nix' -type f | xargs nixfmt --check
          "
      
      - name: Lint check
        run: |
          set -euo pipefail
          nix develop --command bash -c "
            statix check .
          "