name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Check flake and formatting
        run: |
          set -euo pipefail
          echo "Checking flake structure and formatting..."
          nix flake check

      - name: Build packages
        run: |
          set -euo pipefail
          echo "Building all packages..."
          nix build

      - name: Test home configuration build
        run: |
          set -euo pipefail
          echo "Testing home configuration build..."
          nix build --impure .#homeConfigurations.x86_64-linux.runner
